# arbitrage_platform/trading_engine/urls.py
from django.urls import path, include
from rest_framework.routers import DefaultRouter
from .views import ExecuteTradeView, ArbitrageTradeAttemptViewSet, TradeOrderLegViewSet

app_name = 'trading_engine'

router = DefaultRouter()
router.register(r'trade-attempts', ArbitrageTradeAttemptViewSet, basename='arbitragetradeattempt')
router.register(r'trade-legs', TradeOrderLegViewSet, basename='tradeorderleg') # Simple, non-nested

urlpatterns = [
    path('execute/', ExecuteTradeView.as_view(), name='execute_trade'),
    path('', include(router.urls)), # Include URLs generated by the router
]
