# Generated by Django 5.2.3 on 2025-06-21 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="TrackedExchangePair",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_name",
                    models.CharField(
                        choices=[
                            ("Binance", "Binance"),
                            ("Bybit", "Bybit"),
                            ("OKX", "OKX"),
                            ("KuCoin", "KuCoin"),
                            ("Gate", "Gate.io"),
                            ("MEXC", "MEXC"),
                            ("HTX", "HTX"),
                            ("Bitget", "Bitget"),
                            ("Bitfinex", "Bitfinex"),
                            ("BingX", "BingX"),
                        ],
                        max_length=50,
                    ),
                ),
                (
                    "symbol",
                    models.CharField(
                        help_text="Standardized symbol, e.g., BTCUSDT", max_length=30
                    ),
                ),
                (
                    "raw_exchange_symbol",
                    models.CharField(
                        help_text="Symbol as used by the exchange, e.g., BTCUSDT or BTC-USDT",
                        max_length=30,
                    ),
                ),
                ("base_asset", models.CharField(max_length=20)),
                ("quote_asset", models.CharField(max_length=20)),
                (
                    "volume_24h_base",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="24h volume in base asset terms",
                        max_digits=28,
                        null=True,
                    ),
                ),
                (
                    "volume_24h_quote",
                    models.DecimalField(
                        blank=True,
                        decimal_places=8,
                        help_text="24h volume in quote asset terms (e.g., USDT)",
                        max_digits=28,
                        null=True,
                    ),
                ),
                (
                    "last_price",
                    models.DecimalField(
                        blank=True, decimal_places=12, max_digits=28, null=True
                    ),
                ),
                ("last_volume_update", models.DateTimeField(blank=True, null=True)),
                (
                    "is_active_for_scan",
                    models.BooleanField(
                        default=True,
                        help_text="Actively scanned for arbitrage if true and meets liquidity criteria",
                    ),
                ),
                (
                    "precision_rules_json",
                    models.JSONField(
                        blank=True,
                        help_text="Exchange-specific precision rules, lot sizes, etc.",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "Tracked Exchange Pair",
                "verbose_name_plural": "Tracked Exchange Pairs",
                "indexes": [
                    models.Index(
                        fields=["exchange_name", "symbol"],
                        name="market_data_exchang_1d0330_idx",
                    ),
                    models.Index(
                        fields=["is_active_for_scan"],
                        name="market_data_is_acti_a6f69d_idx",
                    ),
                    models.Index(
                        fields=["quote_asset"], name="market_data_quote_a_27539e_idx"
                    ),
                ],
                "unique_together": {("exchange_name", "symbol")},
            },
        ),
    ]
