# Generated by Django 5.2.3 on 2025-06-20 21:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserAPIKey",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "exchange_name",
                    models.CharField(
                        choices=[("Binance", "Binance"), ("Bybit", "Bybit")],
                        max_length=50,
                    ),
                ),
                ("api_key", models.CharField(max_length=255, unique=True)),
                (
                    "_api_secret_encrypted",
                    models.TextField(
                        blank=True, help_text="Encrypted API secret", null=True
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "User API Key",
                "verbose_name_plural": "User API Keys",
                "unique_together": {("user", "exchange_name")},
            },
        ),
    ]
