# Generated by Django 5.2.3 on 2025-06-20 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("key_management", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userapikey",
            name="_api_secret_encrypted",
            field=models.TextField(
                blank=True, help_text="Encrypted API secret (Fernet)", null=True
            ),
        ),
    ]
