# Generated by Django 5.2.3 on 2025-06-20 22:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_management", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("credit", "Credit"),
                            ("debit", "Debit"),
                            ("reversal", "Reversal"),
                            ("initial", "Initial Balance"),
                        ],
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=8, max_digits=19)),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "wallet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="wallet_management.userwallet",
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Transaction",
                "verbose_name_plural": "Wallet Transactions",
                "ordering": ["-timestamp"],
            },
        ),
    ]
