# Generated by Django 5.2.3 on 2025-06-20 23:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("wallet_management", "0002_wallettransaction"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="WalletDepositRequest",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "amount_requested",
                    models.DecimalField(
                        decimal_places=8,
                        help_text="Amount user intends to deposit in USDT",
                        max_digits=19,
                    ),
                ),
                ("currency", models.CharField(default="USDT", max_length=10)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending_user_action", "Pending User Action"),
                            ("pending_confirmation", "Pending Admin Confirmation"),
                            ("completed", "Completed"),
                            ("failed", "Failed"),
                            ("expired", "Expired"),
                        ],
                        default="pending_user_action",
                        max_length=30,
                    ),
                ),
                (
                    "blockchain_tx_id",
                    models.CharField(
                        blank=True,
                        help_text="Blockchain Transaction ID provided by user or found by admin",
                        max_length=255,
                        null=True,
                    ),
                ),
                ("admin_notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deposit_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Wallet Deposit Request",
                "verbose_name_plural": "Wallet Deposit Requests",
                "ordering": ["-created_at"],
            },
        ),
    ]
