# Generated by Django 5.2.3 on 2025-06-20 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trading_engine", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="arbitragetradeattempt",
            name="admin_notes",
            field=models.TextField(
                blank=True,
                help_text="Internal notes for admin, e.g., about commission issues.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="arbitragetradeattempt",
            name="commission_deducted",
            field=models.DecimalField(
                blank=True, decimal_places=8, max_digits=19, null=True
            ),
        ),
        migrations.AddField(
            model_name="arbitragetradeattempt",
            name="error_message",
            field=models.TextField(
                blank=True,
                help_text="Error message if the overall attempt failed.",
                null=True,
            ),
        ),
    ]
